package com.neo.util.framework.microprofile.reactive.messaging.impl;

import com.google.auto.service.AutoService;
import com.neo.util.common.impl.annotation.ProcessorUtils;
import com.neo.util.common.impl.json.JsonUtil;
import com.neo.util.framework.api.connection.RequestContext;
import com.neo.util.framework.api.queue.IncomingQueueConnection;
import com.neo.util.framework.api.queue.QueueListener;
import com.neo.util.framework.api.queue.QueueMessage;
import com.neo.util.framework.impl.connection.QueueRequestDetails;
import com.neo.util.framework.impl.connection.RequestDetailsProducer;
import com.squareup.javapoet.*;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.context.control.RequestContextController;
import jakarta.inject.Inject;
import jakarta.inject.Provider;
import org.eclipse.microprofile.reactive.messaging.Incoming;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.lang.model.util.Elements;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

@SupportedAnnotationTypes("com.neo.util.framework.api.queue.IncomingQueueConnection")
@AutoService(Processor.class)
public class IncomingQueueConnectionProcessor extends AbstractProcessor {

    private static final Logger LOGGER = LoggerFactory.getLogger(IncomingQueueConnectionProcessor.class);

    protected static final String PACKAGE_LOCATION = "com.neo.util.framework.microprofile.reactive.messaging";

    protected static final String BASIC_ANNOTATION_FIELD_NAME = "value";

    protected static final String QUEUE_PREFIX = "from-";

    protected Elements elements;
    protected Filer filer;
    protected Map<String, String> existingIncomingAnnotation = new HashMap<>();
    protected Map<String, String> generatedClasses = new HashMap<>();


    @Override
    public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.latestSupported();
    }

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);
        this.filer = processingEnv.getFiler();
        this.elements = processingEnv.getElementUtils();
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        List<TypeElement> queueConsumerElements = ProcessorUtils.getTypedElementsAnnotatedWith(roundEnv,
                elements, IncomingQueueConnection.class, List.of(ElementKind.CLASS));
        if (queueConsumerElements.isEmpty()) {
            return false;
        }
        LOGGER.debug("Generating associated files for {} annotation", IncomingQueueConnection.class.getName());

        Set<? extends Element> incomingElements = roundEnv.getElementsAnnotatedWith(Incoming.class);
        for (Element element: incomingElements) {
            Parameterizable parameterizable = (Parameterizable) element;
            existingIncomingAnnotation.put(ProcessorUtils.getAnnotationValue(element, Incoming.class,
                            BASIC_ANNOTATION_FIELD_NAME),
                    parameterizable.getEnclosingElement().getSimpleName().toString());
        }
        LOGGER.debug("Existing queues {}", existingIncomingAnnotation);

        for (TypeElement typeElement: queueConsumerElements) {
            ProcessorUtils.checkRequiredInterface(typeElement, QueueListener.class);
            String queueName = ProcessorUtils.getAnnotationValue(typeElement, IncomingQueueConnection.class,
                    BASIC_ANNOTATION_FIELD_NAME);

            String existingQueueAnnotationClass = existingIncomingAnnotation.get(QUEUE_PREFIX + queueName);
            if (existingQueueAnnotationClass != null) {
                LOGGER.debug("Skipping incoming class generation for queue {}. It is already in use in {}", queueName, existingQueueAnnotationClass);
                break;
            }

            String alreadyGeneratedClass = generatedClasses.get(queueName);
            if (alreadyGeneratedClass != null) {
                LOGGER.debug("Skipping incoming class generation for queue {}. It has already been generated by {}", queueName, alreadyGeneratedClass);
                break;
            }

            createConsumeClass(queueName, typeElement);
            generatedClasses.put(queueName, typeElement.getSimpleName().toString());

        }
        return false;
    }

    /**
     * Add temporary fix for
     * https://github.com/oracle/helidon/issues/4681#issuecomment-1223772685
     *
     * @param queueName
     * @param typeElement
     */
    protected void createConsumeClass(String queueName, TypeElement typeElement) {
        try {
            FieldSpec logger = FieldSpec.builder(Logger.class, "LOGGER")
                    .addModifiers(Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                    .initializer("$T.getLogger(" + typeElement.getSimpleName().toString() + "Caller.class)",LoggerFactory.class)
                    .build();

            FieldSpec requestContextFactory = FieldSpec.builder(ParameterizedTypeName.get(Provider.class, RequestContextController.class), "requestContextControllerFactory")
                    .addModifiers(Modifier.PROTECTED)
                    .addAnnotation(Inject.class)
                    .build();
            FieldSpec requestDetailsProducer = FieldSpec.builder(RequestDetailsProducer.class, "requestDetailsProducer")
                    .addModifiers(Modifier.PROTECTED)
                    .addAnnotation(Inject.class)
                    .build();
            FieldSpec queueConsumer = FieldSpec.builder(TypeName.get(typeElement.asType()), "queueConsumer")
                    .addModifiers(Modifier.PROTECTED)
                    .addAnnotation(Inject.class)
                    .build();
            MethodSpec consumeMethodBuilder = MethodSpec.methodBuilder("consumeQueue")
                    .addModifiers(Modifier.PUBLIC)
                    .addAnnotation(AnnotationSpec.builder(Incoming.class)
                            .addMember(BASIC_ANNOTATION_FIELD_NAME,"$S" , QUEUE_PREFIX + queueName).build())
                    .addParameter(String.class, "msg")
                    .addStatement("final var requestContextController = requestContextControllerFactory.get()")
                    .addStatement("requestContextController.activate()")
                    .beginControlFlow("try")
                    .addStatement("final var queueMessage = $T.fromJson(msg, $T.class)", JsonUtil.class, QueueMessage.class)
                    .addStatement("requestDetailsProducer.setRequestDetails(new $T(queueMessage, new $T($S)))",
                            QueueRequestDetails.class, RequestContext.Queue.class, queueName)
                    .addStatement("queueConsumer.onMessage(queueMessage)")
                    .nextControlFlow("catch($T ex)", Exception.class)
                    .addStatement("LOGGER.error($S, ex.getMessage())","Unexpected error occurred while processing a queue [{}], action won't be retried.")
                    .nextControlFlow("finally")
                    .addStatement("requestContextController.deactivate()")
                    .endControlFlow()
                    .build();

            TypeSpec callerClass = TypeSpec.classBuilder(typeElement.getSimpleName().toString() + "Caller")
                    .addModifiers(Modifier.PUBLIC)
                    .addAnnotation(ApplicationScoped.class)
                    .addMethod(consumeMethodBuilder)
                    .addField(queueConsumer)
                    .addField(logger)
                    .addField(requestContextFactory)
                    .addField(requestDetailsProducer)
                    .build();

            JavaFile javaFile = JavaFile.builder(PACKAGE_LOCATION, callerClass).build();

            LOGGER.debug("Generating src file {}Caller", typeElement.getSimpleName());
            javaFile.writeTo(filer);
        } catch (Exception ex) {
            throw new IllegalArgumentException("Unable to generate src file for " + typeElement.getSimpleName().toString(), ex);
        }
    }
}
