package com.neo.util.framework.microprofile.impl.queue;

import com.google.auto.service.AutoService;
import com.neo.util.common.impl.annotation.AnnotationProcessorUtils;
import com.neo.util.common.impl.json.JsonUtil;
import com.neo.util.framework.api.queue.IncomingQueueConnection;
import com.neo.util.framework.api.queue.QueueListener;
import com.neo.util.framework.api.queue.QueueMessage;
import com.squareup.javapoet.*;
import org.eclipse.microprofile.reactive.messaging.Incoming;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.processing.*;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import java.util.*;

@SupportedAnnotationTypes("com.neo.util.framework.api.queue.IncomingQueueConnection")
@SupportedSourceVersion(SourceVersion.RELEASE_11)
@AutoService(Processor.class)
public class IncomingQueueConnectionProcessor extends AbstractProcessor {

    private static final Logger LOGGER = LoggerFactory.getLogger(IncomingQueueConnectionProcessor.class);

    protected static final String PACKAGE_LOCATION = "com.neo.util.framework.microprofile.reactive.messaging";

    protected static final String BASIC_ANNOTATION_FIELD_NAME = "value";

    protected Filer filer;
    protected Map<String, String> existingIncomingAnnotation = new HashMap<>();
    protected Map<String, String> generatedClasses = new HashMap<>();

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);
        this.filer = processingEnv.getFiler();
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        Set<? extends Element> queueConsumerElements = roundEnv.getElementsAnnotatedWith(IncomingQueueConnection.class);
        if (queueConsumerElements.isEmpty()) {
            return false;
        }
        LOGGER.debug("Generating associated files for {} annotation", IncomingQueueConnection.class.getName());

        Set<? extends Element> incomingElements = roundEnv.getElementsAnnotatedWith(Incoming.class);
        for (Element element: incomingElements) {
            Parameterizable parameterizable = (Parameterizable) element;
            existingIncomingAnnotation.put((String) AnnotationProcessorUtils.getAnnotationValue(
                    element.getAnnotationMirrors(), Incoming.class, BASIC_ANNOTATION_FIELD_NAME),
                    parameterizable.getEnclosingElement().getSimpleName().toString());
        }
        LOGGER.debug("Existing queues {}", existingIncomingAnnotation);

        for (Element element: queueConsumerElements) {
            if (element.getKind() != ElementKind.CLASS) {
                throw new IllegalStateException(IncomingQueueConnection.class.getName() +  " must annotate a Class");
            }
            TypeElement typeElement = (TypeElement) element;
            AnnotationProcessorUtils.checkRequiredInterface(typeElement, QueueListener.class);
            String queueName = (String) AnnotationProcessorUtils.getAnnotationValue(element.getAnnotationMirrors(), IncomingQueueConnection.class,
                    BASIC_ANNOTATION_FIELD_NAME);

            String existingQueueAnnotationClass = existingIncomingAnnotation.get(queueName);
            if (existingQueueAnnotationClass != null) {
                LOGGER.debug("Skipping incoming class generation for queue {}. It is already in use in {}", queueName, existingQueueAnnotationClass);
                break;
            }

            String alreadyGeneratedClass = generatedClasses.get(queueName);
            if (alreadyGeneratedClass != null) {
                LOGGER.debug("Skipping incoming class generation for queue {}. It has already been generated by {}", queueName, alreadyGeneratedClass);
                break;
            }

            createConsumeClass(queueName, typeElement);
            generatedClasses.put(queueName, typeElement.getSimpleName().toString());

        }
        return false;
    }

    protected void createConsumeClass(String queueName, TypeElement typeElement) {
        try {
            FieldSpec queueConsumer = FieldSpec.builder(TypeName.get(typeElement.asType()), "queueConsumer")
                    .addModifiers(Modifier.PROTECTED)
                    .addAnnotation(Inject.class)
                    .build();
            MethodSpec consumeMethodBuilder = MethodSpec.methodBuilder("consumeQueue")
                    .addModifiers(Modifier.PUBLIC)
                    .addAnnotation(AnnotationSpec.builder(Incoming.class)
                            .addMember(BASIC_ANNOTATION_FIELD_NAME,"$S" ,queueName).build())
                    .addParameter(String.class, "msg")
                    .addStatement("queueConsumer.onMessage($T.fromJson(msg, $T.class))", JsonUtil.class, QueueMessage.class)
                    .build();

            TypeSpec callerClass = TypeSpec.classBuilder(typeElement.getSimpleName().toString() + "Caller")
                    .addModifiers(Modifier.PUBLIC)
                    .addAnnotation(ApplicationScoped.class)
                    .addMethod(consumeMethodBuilder)
                    .addField(queueConsumer)
                    .build();

            JavaFile javaFile = JavaFile.builder(PACKAGE_LOCATION, callerClass).build();

            LOGGER.debug("Generating src file {}Caller", typeElement.getSimpleName());
            javaFile.writeTo(filer);
        } catch (Exception ex) {
            throw new IllegalArgumentException("Unable to generate src file for " + typeElement.getSimpleName().toString(), ex);
        }
    }

}
